### PR TITLE
update documentation

### PR DESCRIPTION
**Pull request by wardn**

### CODE REVIEW

**Comment by mcduan** [comment]
Thank you for the contribution. Could you sign the CLA as instructed in identity-toolkit-go-client/CONTRIBUTORS first before we can accept your changes?

**Comment by wardn** [comment]
done.

**Comment by mcduan** [comment]
@wardn sorry I couldn't find CLA under your github username. Could you update the CLA to include your github username?
Thanks.

**Comment by wardn** [comment]
done.

**Pull request merged**
